import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
// import Header from "@/components/admin/Header";
// import Footer from "@/components/admin/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//     return (
//         <html lang="en">
//             <body
//                 className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//             >
//                 <Header />
//                 {children}
//                 <Footer />
//             </body>
//         </html>
//     );
// }


// app/(admin-grp)/layout.jsx
import Footer from "@/components/admin/Footer";
import Header from "@/components/admin/Header";
import Aside from "@/components/admin/Aside";

export default function AdminLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="min-h-screen bg-gray-100 flex flex-col">
                    <Header />

                    <div className="flex flex-1">

                        {/* SIDEBAR */}

                        <Aside />
                        {/* MAIN CONTENT */}
                        <main className="flex-1">{children}</main>
                    </div>

                    {/* FOOTER */}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
